### ISSUE TITLE
Too many queries when calling makeChildOf()

### ISSUE THREAD

**Issue by lex0r** [vicklr/materialized-model#2]
I know it sounds vague but executing 20 queries seems too much and is sign of a potential design issue (and a real performance one).

![image](https://user-images.githubusercontent.com/966581/174782005-5145e2af-e0bc-4012-a1ef-1a8ed9403c27.png)

**Comment by MithrandirDK** [comment]
I'm not really sure, why the query to calculate the weight to set would result in excessive queries.

If nothing breaks in the tests when you remove a line of code, I'm thinking that I have missed a(t least one) test. If you want to help me with this, I welcome any PR with accompanying tests.

**Comment by lex0r** [comment]
> I'm not really sure, why the query to calculate the weight to set would result in excessive queries.

This is because the line I mentioned looks for all orphans all the time you do a tree manipulation.

A completely separate point are the excessive updates done to the same items.

> If nothing breaks in the tests when you remove a line of code, I'm thinking that I have missed a(t least one) test. If you want to help me with this, I welcome any PR with accompanying tests.

The PR for the orphan update is as simple as removing the mentioned line. I can't share at this point since I'm doing more changes to the library including Laravel 6.x support.

**Comment by MithrandirDK** [comment]
I have made some changes and refactoring - and I have expanded the tests to cover much more.

I did find why there were too many updates done to the same items, but I can still not confirm that removing the mentioned line is a good move. Actually, with the increased test coverage, removing the line will now result in a test fail.

Since there have been numerous changes, I suggest you look at version 2.0.1 and see if your issue is still relevant. If so, PR's are welcomed.
